## YAML FILE for package "rp_semantic".

#------------------------------------------------
# Computer dependent parameters
#------------------------------------------------

# Caffe configuration
rp_semantic/caffe_root_path: '/home/albert/GitHub/caffe-segnet-cudnn5/'
rp_semantic/caffe_model_path: '/home/albert/rp_data/'

# Descriptor storage parameters
rp_semantic/descriptor_file: '/home/albert/rp_data/descriptors.txt'

#------------------------------------------------
# Debugging
#------------------------------------------------

rp_semantic/publish_rgb_frame: true
rp_semantic/publish_rgb_labels: true

rp_semantic/publish_cluster_markers: false # TODO fix visualization message

#------------------------------------------------
# Algorithm parameters
#------------------------------------------------

# Reshape size for net output to match with camera intrinsics matrix
rp_semantic/sensor_image_height: 480
rp_semantic/sensor_image_width: 640

# Cluster parameters
rp_semantic/clusters_node/cluster_tolerance : 0.04 # in cm.
rp_semantic/clusters_node/min_cluster_size : 500
rp_semantic/clusters_node/max_cluster_size : 75000 # 50000

# Matching parameters
rp_semantic/BOWP_matching/dist_exponent : 3.0



